name: AI_CORE_DEPLOY_ON_PUSH

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: actions/setup-python@v5.1.0
      - name: Unzip VCTL
        run: |
          ls
          pwd
      - name: Run deploy script
        run: |
          pip install -r ./cicd/requirements.txt
          AICORE_AUTH_URL='${{ secrets.AICORE_AUTH_URL }}' AICORE_CLIENT_ID="${{ secrets.AICORE_CLIENT_ID }}" AICORE_CLIENT_SECRET='${{ secrets.AICORE_CLIENT_SECRET }}' AICORE_RESOURCE_GROUP='${{ secrets.AICORE_RESOURCE_GROUP }}' AICORE_BASE_URL='${{ secrets.AICORE_BASE_URL }}' python ./cicd/pipeline.py
